### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by MarkioE** [MarcFletcher/NetworkComms.Net#17]
Have you looked into support for .NET core yet?

**Comment by MarcFletcher** [comment]
Heya MarkioE, I believe our support for Windows RT is compatible with .NET core. If you believe otherwise please let me know.

**Comment by moro91** [comment]
No, it's not. I just tried to port it into a NuGet Package to include a reference to the WinRT assembly from a .NET Core library. When adding the reference, visual studio says that Protobuf and 32feet.net aren't compatible with netstandard1.6. Is there a way to fix this? Are there versions of these two dependencies for .NET Core?

**Comment by moro91** [comment]
Oh, one more thing: i created the package starting from the "All-in-one" merged assembly

**Comment by MarcFletcher** [comment]
You'll most likely need to avoid using the All-in-one assembly for lightweight frameworks (RT, Core etc), as this includes a large number of features not supported outside full .net. Please let me know if you have similar issues with just the core NetworkComms.Net assembly.

**Comment by moro91** [comment]
Ok but, as I imagine, Protobuf and 32feet.net are still dependencies of the core assembly. Otherwise, how could the serialization & bluetooth functionalities be present in the final lib?

However, i just tried creating the NuGet package from the simple core assembly in WinRT project and referencing it from a .NET Core application.

Same error, same dependencies cannot be resolved while resoring the NuGet package :(

**Comment by MarcFletcher** [comment]
The core library supports only .Net `ISerializable` and `NullSerializers`, both protobuf and 32feet.net are outside of the core to maintain cross platform compatibility. I'm not sure where the dependencies from these would be coming from?

**Comment by moro91** [comment]
I'm exploring the solution you shared here. Can you please target me to the right path of the right project i have to build? This would help me creating a clear NuGet package and a clear referenceable version for .NET Core ready-to-use

**Comment by MarcFletcher** [comment]
https://github.com/MarcFletcher/NetworkComms.Net/tree/master/NetworkCommsDotNet is the correct project. Please see the compile time flags that have already been scattered around the place, as an example see the static initializer in https://github.com/MarcFletcher/NetworkComms.Net/blob/master/NetworkCommsDotNet/NetworkComms.cs

**Comment by moro91** [comment]
Ok, i was in the right point. No re-targeting for .NET Core is selectable in the project properties. Compiling them with the AnyCPU configuration is bringing all the dependencies i expect in the .net framework version. What's the build profile you intended to use for keeping the compile time flags consistent?

**Comment by MarcFletcher** [comment]
Please see https://msdn.microsoft.com/en-us/library/4y6tbswk.aspx. The project can be built with multiple different compile time flags depending on the desired platform.

**Comment by codybin** [comment]
hey,i come from china,i am 28now,but i want to study program,do u have some advice for me?i  want to study socket communication with c#.how to start,zhengjiabin1989@sina.com is my mail
