### ISSUE TITLE
Get a file from local network folder

### ISSUE THREAD

**Issue by akhalid** [MarcFletcher/NetworkComms.Net#18]
Hello,

Just getting started with NetworkComms. I wanted to know if there is a way to get specific file types (.txt, .bmp, etc.) from a local network folder. Essentially my app will be polling this folder and as soon as a file is dropped into that folder, I will need to transfer the file from the network folder to the host PC local directory.

Thanks!

AK

**Comment by MarcFletcher** [comment]
Please see the included FileTransferExample that you could modify for your required purchase.

**Comment by akhalid** [comment]
Thanks for the response. In the example we have 2 instances of the filetransfer application running on 2 machines on the same network. My question is that if I have shared folder on the network. How can I use NetworkComms to check that folder for available files. So only 1 instance of NetworkComms running. Thank you for your time.
