### ISSUE TITLE
Possible Issue with Examples in Visual Studio 2015

### ISSUE THREAD

**Issue by jpvdmerwe** [MarcFletcher/NetworkComms.Net#21]
Hi,

I am trying to use the examples provided in Visual Studio 2015, however I keep getting the following error:

Specified cast is not valid.

Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/14326866/17657522/6e7c11d6-62c4-11e6-892f-c025ced60454.png)

The examples work fine in Visual Studio 2012.

**Comment by MarcFletcher** [comment]
This sounds like some sort of build inconsistency with your VS 2015 install. I have it running ok in 2015.
