### ISSUE TITLE
Is there a cross-platform plan?

### ISSUE THREAD

**Issue by objectboy2016** [MarcFletcher/NetworkComms.Net#22]
A cross-platform plan? For example, running on Linux

**Comment by MarcFletcher** [comment]
If you use Mono.Net it already run's in Linux.

**Comment by snekbaev** [comment]
I guess question is more regarding the .NET Core. I'm also searching for some networking library at the moment, but main concern is obviously about the development plan. I'd love to use NetworkComms now if I knew for sure that next year it (or at least the core part) will be compatible with .NET Standard 2.0 library

**Comment by MarcFletcher** [comment]
I have always been under the impression that RT (which we already support) is compatible with Core. Supported platforms include:

- .net 2+ compatible languages (C#, VB .Net, F#, J#, C++/CLI etc)
- Mono 2.10+ (Linux, Unity3D, MonoGame etc)
- iOS (Xamarin.iOS)
- Android (Xamarin.Android)
- Windows Phone 8
- Windows Store (RT & Metro)

**Comment by snekbaev** [comment]
Not sure about that. But I definitely know that 2.0 version is a sort of an API unification across the .NET. I'll wait until some RC and will start migrating current projects, given that most dependencies will be up to date with it.

**Comment by MarcFletcher** [comment]
To ensure I've answered the OPs post, we don't currently have a roadmap for any additional platforms. As networkcomms.net was built on .net2 however, we've found that the number of changes to support additional platforms has actually been incredibly light weight. As such if anyone would like to give other platforms a shot, we should happily review a PR.
