### ISSUE TITLE
Sending List<CustomObject> not possible

### ISSUE THREAD

**Issue by alainbelez** [MarcFletcher/NetworkComms.Net#23]
how do you send a List<CustomObject>?

i tried it already and implemented IExplicitlySerialize on CustomObject and realized that List should also implement it, should i extend the List Class?

**Comment by MarcFletcher** [comment]
You need to create a wrapper for the list:

```
public class ListWrapper {
    public List<CustomObject> myList;
}
```

and then send the wrapper.

M
