### ISSUE TITLE
Networkcomms for iOS inside of Unity not working

### ISSUE THREAD

**Issue by 0x-1** [MarcFletcher/NetworkComms.Net#24]
Hey,

I can't get Networkcomms to work inside Unity on a iOS platform.
What is the difference between the Networkcomms.IOS version and the .net 3.5?
What makes the one work in iOS and the other not?

I tried to include the Networkcomms.IOS in Unity but it can't refactor it due to the 4.5 framework.
I tried to compile a 3.5 version of Networkcomms.IOS but that did not work either as the Xamarin.IOS library is missing.

**Comment by 0x-1** [comment]
Does Networkcomms use System.Reflection?

https://docs.unity3d.com/Manual/iphone-playerSizeOptimization.html

**Comment by 0x-1** [comment]
I'm getting a null reference in
NetworkCommsDotNet.DPSBase.DPSManager.CreateObjectWithParameterlessCtor (System.string typeName)
NetworkCommsDotNet.DPSBase.DPSManager.GetDataSerializer[T] ()
NetworkCommsDotNet.DPSBase.DPSManager.<.ctor>b__l ()

**Comment by MarcFletcher** [comment]
Reflection should only be used for additional serializers. Please try only using the nullserializer for testing purposes to see if you get the same error. Another thing you could try is to add a hardcoded reference to any required code before compiling for unity to again confirm that is the cause.

**Comment by 0x-1** [comment]
Could not figure it out and don't have much time left.
Switched to a Restful networking solution instead.
