### ISSUE TITLE
Message never gets received

### ISSUE THREAD

**Issue by Pyroglyph** [MarcFletcher/NetworkComms.Net#27]
Using breakpoints I can see that the server sends a response message, but the client never receives it.
Sample code below:

## Client
    class Program
    {
        static void Main(string[] args)
        {
            NetworkComms.AppendGlobalIncomingPacketHandler<bool>("Response", (header, connection, message) =>
            {
                //
                //
                // MESSAGE SHOULD BE RECEIVED HERE, BUT ISN'T
                //
                //
                Console.WriteLine("\nA login response was received from " + connection.ConnectionInfo.RemoteEndPoint + " which said '" + message + "'.");
            });
            //Start listening for incoming connections
            Connection.StartListening(ConnectionType.TCP, new IPEndPoint(IPAddress.Any, 0));

            //Request server IP and port number
            Console.WriteLine("Please enter the server IP and port in the format 192.168.0.1:10000 and press return:");
            var serverInfo = Console.ReadLine();
            if (serverInfo == string.Empty) serverInfo = "127.0.0.1:2048";

            //Parse the necessary information out of the provided string
            var serverAddr = serverInfo.Split(':').First();
            var serverPort = int.Parse(serverInfo.Split(':').Last());

            //Keep a loopcounter
            var loopCounter = 1;
            while (true)
            {
                //Write some information to the console window
                var messageToSend = "Jeff";
                Console.WriteLine("Sending message to server saying '" + messageToSend + "'");

                //Send the message in a single line
                NetworkComms.SendObject("Login", serverAddr, serverPort, messageToSend);

                //Check if user wants to go around the loop
                Console.WriteLine("\nPress q to quit or any other key to send another message.");
                if (Console.ReadKey(true).Key == ConsoleKey.Q) break;
                loopCounter++;
            }

            //We have used comms so we make sure to call shutdown
            NetworkComms.Shutdown();
        }
    }

## Server

    class Program
    {
        private const int Port = 2048;

        private static readonly List<string> UserList = new List<string>();

        static void Main(string[] args)
        {
            //We expect the incoming object to be a string which we state explicitly by using <string>
            NetworkComms.AppendGlobalIncomingPacketHandler<string>("Login", (header, connection, name) =>
            {
                Console.WriteLine("\nA message was received from " + connection.ConnectionInfo.RemoteEndPoint + " who wants to be called '" + name + "'.");

                var ip = connection.ConnectionInfo.RemoteEndPoint.ToString().Split(':')[0];
                var port = int.Parse(connection.ConnectionInfo.RemoteEndPoint.ToString().Split(':')[1]);

                var allowedIn = true;
                
                for (var i = 0; i < UserList.Count; i++)
                {
                    if (UserList[i] == name)
                    {
                        Console.WriteLine(name + " is not allowed in since there is already a user with that name.");
                        NetworkComms.SendObject("Response", ip, port, false);
                        allowedIn = false;
                    }
                }

                if (UserList.Count == 0) allowedIn = true;

                if (allowedIn)
                {
                    Console.WriteLine(name + " has joined!");
                    UserList.Add(name);
                    //
                    //
                    // MESSAGE IS SENT HERE
                    //
                    //
                    NetworkComms.SendObject("Response", ip, port, true);
                }
            });
            //Start listening for incoming connections
            Connection.StartListening(ConnectionType.TCP, new IPEndPoint(IPAddress.Any, Port));

            //Print out the IPs and ports we are now listening on
            Console.WriteLine("Server listening for TCP connection on PORT " + Port);

            while (true)
            {
                Console.Clear();
                
                Console.WriteLine("User List:");
                for (var i = 0; i < UserList.Count; i++)
                {
                    Console.WriteLine("\t" + UserList[i]);
                }

                Thread.Sleep(100);
            }
            
            //We have used NetworkComms so we should ensure that we correctly call shutdown
            //NetworkComms.Shutdown();
        }
    }

I'm using Win10 Pro 64-bit and VS Community 2017.

**Comment by MarcFletcher** [comment]
I would suspect this is a firewall issue. If you are still experiencing the problem please feel free to reply to this ticket and I will reopen.
