### ISSUE TITLE
TCP: Receiving packet in Xamarin.iOS

### ISSUE THREAD

**Issue by zelsius** [MarcFletcher/NetworkComms.Net#28]
NetworkComms.Net Version: 3.0.3
When trying to receive an object by either using NetworkComms AppendGlobalIncomingPacketHandler or SendReceiveObject in Xamarin.iOS it crashes with System.NotSupportedException error.
Using the same code in a WinForms application works perfectly fine.

	`		public static void TestNMEA()
		{
			NetworkComms.AppendGlobalIncomingPacketHandler<string>("ResponseGPSCoordinates", PrintIncomingMessage);

			NetworkComms.SendObject("RequestGPSCoordinates", "192.168.1.80", 50000, "Hello Worldas");
			//var result = NetworkComms.SendReceiveObject<string, string>("RequestGPSCoordinates", "192.168.1.80", 50000, "ResponseGPSCoordinates", 500000, "Hello");
		}

		private static void PrintIncomingMessage(PacketHeader header, Connection connection, string message)
		{
			Debug.WriteLine("\nA message was received from " + connection.ToString() + " which said '" + message + "'.");
		}

`

![screen shot 2017-07-20 at 13 30 43](https://user-images.githubusercontent.com/15330742/28415449-2378fe28-6d50-11e7-8e38-ef0c449b06bb.png)

**Comment by zelsius** [comment]
I managed to resolve this issue by updating the Nuget packages of the NetworkComms source and creating a new dll file for Xamarin.iOS, but now I am struggling with messages not arriving at the iOS device.
I'll let you know if I find out anything.

**Comment by MarcFletcher** [comment]
Many thanks for the update.
