### ISSUE TITLE
PacketHandlerErrorGlobal_File Overload

### ISSUE THREAD

**Issue by Its-Jeremy-B** [MarcFletcher/NetworkComms.Net#30]
On my server, I seem to be getting bombarded by these. However, I have followed all steps accordingly and my server seems to be transferring information at high speeds with no loss. Sounds like a bug to me, but that's not my call I guess.

**Comment by JBlevins1996** [comment]
![packethandler errors](https://user-images.githubusercontent.com/31716527/30143013-afeea034-9351-11e7-8fd3-b4f4003789ae.PNG)

**Comment by MarcFletcher** [comment]
Something is definitely odd! If you could zip up the all of those files and attach them to the ticket (assuming there is no confidential data in there) I'd be happy to try and work out the issue! Also if you have code samples from the parts of code throwing the error that would also help.

**Comment by JBlevins1996** [comment]
Hello Marc,

 

I got those PacketHandler errors again. Take a look here. I’m getting them more often when I have more than around 10 users connected to my server at once. Take a look and let me know what you think.

 

Thanks

**Comment by MarcFletcher** [comment]
I'm going to close this issue as you didn't provide the necessary information. Without more information, e.g. the contents of the error files, it would be very hard to provide any assistance.
