### ISSUE TITLE
NetworkCommsDotNet.ConnectionSetupException

### ISSUE THREAD

**Issue by mridah** [MarcFletcher/NetworkComms.Net#33]
When I use the sample code to send data, it  doesn't work and gives this exception in the message console:
> NetworkCommsDotNet.ConnectionSetupException

This happens even when I have the server running.

The reason given is: Error during TCP connection establish with destination....

**Client code:**

    try
          {
                String messageToSend = "this is a test message";
                NetworkComms.SendObject("Message", SERVER_IP, PORT_NO, messageToSend);
          }
    catch (Exception e)
    {
           DoGUIStatus(e.ToString().Substring(0, 160));
     }

**Server code:**

    private void StartListening()
    {
         try
         {
             NetworkComms.AppendGlobalIncomingPacketHandler<string>("Message", DisplayIncomingData);
             Connection.StartListening(ConnectionType.TCP, new System.Net.IPEndPoint(System.Net.IPAddress.Any, 0));
             DoGUIStatus("Started listening");
         }
         catch(Exception e)
         {
             DoGUIStatus(e.ToString() + "Could not start listening");
         }
     }

     private void DisplayIncomingData(PacketHeader header, Connection connection, string message)
     {
          Console.WriteLine("\nA message was received from " + connection.ToString() + " which said '" + message + "'.");
          DoGUIStatus(message);
     }

Any idea why this is happening ?? @MattDean @pashcovich

**Comment by mridah** [comment]
The client program is sending data at port 5000. When I ping server via telnet so check if port 5000 is open, it displays:
> Connecting To 192.168.0.30...Could not open connection to the host, on port 5000: Connect failed
This is my current IP address. This is happening even when my server is running. The `Connection.StartListening(..)` command didn't throw any exceptions, so it should have worked.

Is there any way I can specify to the server to listen at a particular port ?

**Comment by MarcFletcher** [comment]
These kinds of issues are normally caused due to port restrictions or firewalls on your server/client. If you look through the code of https://github.com/MarcFletcher/NetworkComms.Net/blob/master/ExamplesConsole/AdvancedSend.cs you'll see:

```
//Start listening for incoming connections
//We want to select a random port on all available adaptors so provide 
//an IPEndPoint using IPAddress.Any and port 0.
//If we wanted to listen on a specific port we would use that instead of '0'
Connection.StartListening(connectionTypeToUse, new IPEndPoint(IPAddress.Any ,0));
```

so if you want to use a different server port just change the '0' to something you know should work.
