### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by Laur-lct** [MarcFletcher/NetworkComms.Net#34]
Hello,

Are there any plans to support .net core  for this library?
If this is in place, it can be a really good alternative to WCF, as they are not planning to have that.

**Comment by MarcFletcher** [comment]
Thanks for the question. It should be entirely possible to add such support as the necessary compile flags are already in place for other library versions across the core project. Unfortunately it's not something the original contributors currently have time to add. We would gratefully welcome any external contributions that add this support though.
