### ISSUE TITLE
UDP Broadcast not received on Raspberry Pi 3

### ISSUE THREAD

**Issue by Peter-Krebs** [MarcFletcher/NetworkComms.Net#36]
Thanks for making this library, I like the concept!

As the title suggests: I've tried to make a UDP broadcast work on two Raspberry Pi boxes, connected to the same router as my laptop. They seemingly cannot talk to each other using NetworkComms.
There are no errors output or exceptions thrown while the application is running.

I need the Raspberrys to broadcast to each other. Is my usage of your library at fault here or do you have any pointers? How can I provide further info for debugging NetworkComms's part of things?

**Versions**  
NetworkComms 3.0.3  
Raspberrry Pi 3  
.NET Framework 4.6.1
mono 4.6.2
OS: Raspbian Lite - Raspbian GNU/Linux 9 (stretch)

**Source code**
```C#
using NetworkCommsDotNet;
using NetworkCommsDotNet.Connections;
using NetworkCommsDotNet.Connections.UDP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace UdpExample
{
    class Program
    {
        static void Main(string[] args)
        {
            NetworkComms.AppendGlobalIncomingPacketHandler<string>("ChatMessage",
                (packetHeader, connection, incomingString) =>
                {
                    Console.WriteLine("\n  ... Incoming message from " +
                        connection.ToString() + " saying '" +
                        incomingString + "'.");
                });

            //Start listening for incoming UDP data
            Connection.StartListening(ConnectionType.UDP, new IPEndPoint(IPAddress.Any, 10000));

            Console.WriteLine("Type ESC to quit.");
            do
            {
                while (!Console.KeyAvailable)
                {

                    UDPConnection.SendObject("ChatMessage", "This is the broadcast test message!", new IPEndPoint(IPAddress.Broadcast, 10000));

                    Task.Delay(2000).Wait();
                }
            } while (Console.ReadKey(true).Key != ConsoleKey.Escape);

            NetworkComms.Shutdown();
        }
    }
}
```

**SSH Session**  
When starting the program on two raspberries, they don't receive messages (console window does not print the received ChatMessage):
![20181113-1-udp-10000 ssh-session](https://user-images.githubusercontent.com/43567035/48422328-bab27600-e75e-11e8-9433-27fc3bd704a6.png)

**Wireshark sees broadcasts**  
Meanwhile... the broadcasts can be seen in Wireshark:
![20181113-1-udp-10000 wireshark](https://user-images.githubusercontent.com/43567035/48422387-d3bb2700-e75e-11e8-83d1-6651daddc180.png)

**Netcat works**  
A netcat session reveals that send/receive should work, so it's not likely a configuration issue:
![20181113-1-udp-10000 netcat](https://user-images.githubusercontent.com/43567035/48422480-06651f80-e75f-11e8-906a-3da52b450435.png)

Thanks in advance!

**Comment by MarcFletcher** [comment]
Couple of things for you to try:

1. We have an included chat app example that you can configure to use UDP, I think it's in the AdvancedTest file. Does that work? 
2. Try using TCP to make sure the two devices can connect to one another and are not firewalled in some instances. Looks like you might be on windows, in which case make sure you have all firewalls turned off during the tests.

If that doesn't work let me know.

**Comment by Peter-Krebs** [comment]
Thanks for the pointers!

  1. The example worked partially. I selected Custom object, no compression, no encryption.  
    The example works for UDP when entering the target IP and port.  
    Sending a UDP broadcast did not work. See Screenshot below.
  2. I'm developing on a Windows machine, yes, but the code runs on two Raspberry Pis (www.raspberrypi.org) using Mono.
    The example with netcat from my OP shows both Raspberry Pi receive broadcast messages in general. There is no Windows machine involved during that.
    If there was a firewall issue I wouldn't have seen the broadcast packages with WireShark, but they're there.
    If the raspberry's had an active firewall (which I deactivated) the netcat broadcasts wouldn't have come through either, but they do.

We need the UDP broadcast for discovering other hosts. Manually looping through IP ranges would take forever in comparison and is not future-proof regarding IPv6 address ranges.

*Screenshot*: Output of the AdvancedSend example:  
Sending 3 and "Three" works when explicitly stating IP + port.  
Sending 4 and "Four" with a broadcast is not received on the other end.

![20181122-1-udp-advancedsend ssh-session](https://user-images.githubusercontent.com/43567035/48914484-e4188380-ee7b-11e8-8df7-30a2d8c318fc.png)

Any ideas?

**Comment by MarcFletcher** [comment]
Yea, I take your points about the wireshark stuff. From experience UDP broadcasting can be problematic with some hardware. It might be for some reason the broadcast packets are not being sent up the network stack correctly on the pi's, but that's outside my area of expertise.

For reference if your trying to broadcast between two .net native machines on the same network it works quite well (http://www.networkcomms.net/udp-broadcasting/). Perhaps if you have the machines that's another thing to try that might then point the finger directly at a mono issue or pi issue.

**Comment by MarcFletcher** [comment]
Am closing this as it's now stale and we never got to the bottom of this ext issue.

Many thanks for the discussion.
