### ISSUE TITLE
Custom message framing

### ISSUE THREAD

**Issue by bangar1991** [MarcFletcher/NetworkComms.Net#37]
Hi, thanks for this wonderful project. I was hoping to use it in my application for its high networking performance and some abstraction from thready safety issues.

However, looking at the API and the tutorials, it seems that the library relies on `PacketHeader` and the like to implement its own message framing/serialization. How do I bypass that to implement a custom protocol that uses simple length prefixing instead? Any help would be appreciated.

**Comment by MarcFletcher** [comment]
See the uses of ConnectionInfo.ApplicationLayerProtocol. If you set this to disabled you'll be able to configure your own protocol.
