### ISSUE TITLE
Not an Issue but a feature request

### ISSUE THREAD

**Issue by himanshukodwani** [MarcFletcher/NetworkComms.Net#38]
Is there a possibility to encrypt communication using Public/Private key handshake.
1) Client requests server for its public key. (Handshake)
2) The client sends all its messages which includes clients public key. This message is encrypted by the server's public key.
3) The server receives the message/request etc and decrypts it with the server's private key. Then it does it's work and sends the response to the client encrypted by the client's public key,
4) The client receives the message and decrypts it with its private key.

This kind of encryption will remove the dependency on Pre sharing a key.

**Comment by MarcFletcher** [comment]
Many thanks for getting in touch.

This should be possible if you define https://github.com/MarcFletcher/NetworkComms.Net/blob/master/NetworkCommsDotNet/Connection/TCP/SSLOptions.cs when creating a connection.

Kind regards,
Marc

**Comment by himanshukodwani** [comment]
Dear Marc,
Thanks a lot for pointing this out. I’ll be obliged if you’d point me towards a complete sample or a working example.
Thanks and best regards,
Himanshu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
