### ISSUE TITLE
RPC : Generic Parent Service Interface 

### ISSUE THREAD

**Issue by himanshukodwani** [MarcFletcher/NetworkComms.Net#39]
//Common Interfaces

public interface ISettingsService : IBaseService<Settings> 
{
     Settings  GetBy_SettingName(string settingName);
}
public interface IBaseService<T> where T : IProtoBuffEntity
{
     bool Delete(T entity);
     bool Create(T entity);
     bool Update(T entity);
     IList<T> GetAll(int recordsPerPage, int pageNumber);
     int GetRecordsCount();     
}

//Above ISettingsService is an interface which is mapped to a service on the server 
//ClinetProxyCreation where T is ISettingsService
remoteObject = RemoteProcedureCalls.Client.CreateProxyToPrivateInstance<T>(connection, "ISettingsService".ToLower(), out instanceId);

I get following error on client side
The type initializer for 'Cache`1' threw an exception.The type initializer for ' Cache`1' threw an exception.
System.TypeLoadException: Method 'Delete' in type 
'XXXX.ServerModules.grp_ISettingsService'

**Comment by MarcFletcher** [comment]
Have you followed our included [RPC example](https://github.com/MarcFletcher/NetworkComms.Net/blob/master/ExamplesConsole/RPCExample.cs) to build that solution. I don't recognise the exception so my first guess would be it's something specific about your implementation. 

An additional question I'd ask is 'If you remove the Delete method do the other ones that return bool throw a similar exception?'. If not that might help you narrow down what's specific to Delete.

Best of luck.

**Comment by himanshukodwani** [comment]
Hi !
Thanks for the reply.
This problem solves if I redefine parent interface members again in the child interface. But then, that is not a good practice.
Thanks for your effort.
Good luck

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MarcFletcher** [comment]
👍
