### ISSUE TITLE
How to disable error files

### ISSUE THREAD

**Issue by CyberFranck** [MarcFletcher/NetworkComms.Net#40]
We have a large central application using the libraries and couple hundreds computer has a remote viewer app that all it does is listen to the server events and display data. It's only incoming data. But the same application create a bunch a txt error files beside the exe and flood the folder overtime. I am wondering how we can disable all these file creation. The software works perfectly on these computers there is no issue whatsoever other than those annoying files.

I need to mention that this issue don't happen on all computers. It's about 50/50.

name of the files are starting with these names :
ManagedThreadPoolCallBackError
CompleteIncomingItemTaskError
PacketHandlerErrorGlobal_Notification

We tried using the following without success.
NetworkComms.DisableLogging();

It's not a big issue, we can code something to check for those file name and delete but i was looking for a cleaner solution.

**Comment by MarcFletcher** [comment]
Many thanks for getting in touch. 

I agree it should be possible to disable those output files. Logically perhaps by using `NetworkComms.DisableLogging();`. Unfortunately that's not have the output of those fatal errors in handled by 'https://github.com/MarcFletcher/NetworkComms.Net/blob/master/NetworkCommsDotNet/Tools/LogTools.cs'. In addition to your suggestion of having a cleanup operation you could also modify the LogTools class directly or via reflection to disable the methods.

I'll leave this as a feature request for future reference.

**Comment by MarcFletcher** [comment]
I'm considering getting rid of the old .net version builds and using something more 'recent' ;) Just to ensure this suits your use case can you please confirm with me that a release targeting .net framework 4.8.1 would be ok for you?

**Comment by CyberFranck** [comment]
We thought the project was dead. We were and are still in .net 4.8. We started looking into upgrading to .NET 8.0 so we can look at this library anymore. Although the simplicity of it is staggering compared to the rest out there

**Comment by MarcFletcher** [comment]
A pre-release package of 3.0.4 is now available on nuget if you'd like to confirm this works for you - https://www.nuget.org/packages/NetworkCommsDotNet/3.0.4-beta. This version doesn't create error files unless logging is enabled.

Following this we will also release a .net8 version.

**Comment by MarcFletcher** [comment]
A full release of 3.0.4 has now been made available on nuget. Sorry for the delay! We'll also start work on supporting .net 8 next.
