### ISSUE TITLE
Having an issue with EnableDiscoverable

### ISSUE THREAD

**Issue by Smithangshu** [MarcFletcher/NetworkComms.Net#41]
Hi,

First of all, thank you for sharing such a wonderful library. 

I am having an issue with this code.

`HostInfo.IP.RestrictLocalAddressRanges = new IPRange[] { new IPRange(txtRangeStart.Text), new IPRange(txtRangeEnd.Text) };
PeerDiscovery.EnableDiscoverable(PeerDiscovery.DiscoveryMethod.UDPBroadcast);`

I am supplying Range Start as 127.0.01/32 and 192.168.2.0/32. The IP of current PC is 192.168.1.40.  The other Peer is running on 192.168.2.35. 

But this Peer is always failing at start when it reach the above mentioned portion of the code saying "Failed to find local available port on address 192.168.2.69 while trying to make this peer discoverable. Consider increasing the available port range via MinTargetLocalIPPort and MaxTragetLocalIPPort."

But strange is that 192.168.2.69 is not being used by any other PC in network. It's unused IP in that network. If I specifically use this IP in end range using 192.168.2.69/32, it generates same error. Also 192.168.2.68 is another unused IP in the network. But if I specify end range as 192.168.2.68/32 it does not reflect same issue, it works fine. Problem only occurring when 192.168.2.69 IP comes across in range or specifically set.

Can you please help me? Thanks in advance.

**Comment by MarcFletcher** [comment]
Thanks for letting us know you like the library.

One of the challenges of peer discovery is that there can be other services running on your network which might  interfere. 

A couple of options you could try:
1. Perhaps try a different port number in the range 1024 to 49151. This can be configured by modifying PeerDiscovery.MinTargetLocalIPPort  and MaxTargetLocalIPPort.
2. You could try using DiscoveryMethod.TCPPortScan instead.
3. You could change the PeerDiscovery.ListenMode on the clients you are trying to discover. It might be the other modes work better.
4. You could try using the `PeerDiscovery.EnableDiscoverable(...` method that allows you to specify an explicit `localDiscoveryEndPoint`

Fingers crossed one of those works for you.

Good luck,
Marc

**Comment by Smithangshu** [comment]
Hi Marc,

I have overcome the issue with solution that you have provided in option 4. It works perfectly. Thank you so much.

Two more question, 
1) Is there any specific reason to not use TCP Scan as I have seen in the doc that is not recommended?
2) Can I use Shared FileSystem when my Peers are connected using UDP protocol?

Regards,
Smithangshu

**Comment by MarcFletcher** [comment]
Thanks for the feedback, great to hear it resolved your issue.

Answers to your questions:
1. TCP Scan isn't as efficient as it needs to check every IP individually and has a higher network overhead. When using UDP discovery NetworkComms.net can take advantage of [UDP broadcast](https://en.wikipedia.org/wiki/Broadcast_address).
2. If you're referring to the DistributedFileSystem this uses both UDP and TCP depending on the different parts of the process to try and maximise performance.
