### ISSUE TITLE
.Net MAUI support

### ISSUE THREAD

**Issue by jeffwhitty** [MarcFletcher/NetworkComms.Net#44]
Hi all!

Loving your library, it's made it super easy to handle a server/client subscriber model in my WPF application. I went down this path due to the promise of being able to use it in IOS to talk to the same WPF app, and with MAUI coming out recently I've started to dabble there... Any plans to lift this up to MAUI?

Thanks

Jeff

**Comment by MarcFletcher** [comment]
Thanks very much for your support. Mainly due to a lack of resources we don't have any plans to make this library MAUI compatible. We are as always happy to work with contributors if they raise PRs to make changes.
